class TermsOfService {
  final String heading;
  final String details;

  TermsOfService({required this.heading, required this.details});
}

List<TermsOfService> terms = [
  TermsOfService(
      heading: 'Genral Terms',
      details:
          'By accessing and placing an order with Athlink, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and Athlink.  Under no circumstances shall Athlink team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if Athlink team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.  Athlink will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment. This Privacy Policy was created with Termify.io'),
  TermsOfService(
      heading: 'Liesence',
      details:
          'Athlink grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the app strictly in accordance with the terms of this Agreement.  These Terms & Conditions are a contract between you and Athlink (referred to in these Terms & Conditions as "Athlink", "us", "we" or "our"), the provider of the Athlink website and the services accessible from the Athlink website (which are collectively referred to in these Terms & Conditions as the "Athlink Service").  You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Athlink Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.'),
  TermsOfService(
      heading: 'Meanings',
      details:
          '  -Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.   -Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Athlink, that is responsible for your information under this Terms & Conditions.   -Country: where Athlink or the owners/founders of Athlink are based, in this case is United States   -Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Athlink and use the services.   -Service: refers to the service provided by Athlink as described in the relative terms (if available) and on this platform.   -Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.   -Website: Athlink."’s" site, which can be accessed via this URL:    -You: a person or entity that is registered with Athlink to use the Services.'),
  TermsOfService(
      heading: 'Restrictions',
      details:
          'You agree not to, and you will not permit others to:    -License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the app or make the platform available to any third party.   -Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the app.   -Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of Athlink or its affiliates, partners, suppliers or the licensors of the app.    '),
  TermsOfService(
      heading: 'Return and Refund Policy',
      details:
          '  Thanks for shopping at Athlink. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.  As with any shopping experience, there are terms and conditions that apply to transactions at Athlink. We’ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at Athlink, you agree to the terms along with Athlink."’s" Privacy Policy.  If, for any reason, You are not completely satisfied with any good or service that we provide, dont hesitate to contact us and we will discuss any of the issues you are going through with our product.   '),
  TermsOfService(
      heading: 'Your Suggestions',
      details:
          'Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to Athlink with respect to the app shall remain the sole and exclusive property of Athlink.  Athlink shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.'),
  TermsOfService(
      heading: 'Your Consent',
      details:
          "  We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our app, registering an account, or making a purchase, you hereby consent to our Terms & Conditions."),
  TermsOfService(
      heading: 'Links to Other Websites',
      details:
          'This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by Athlink. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about yo'),
  TermsOfService(
      heading: 'Cookies',
      details:
          ' Athlink uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.'),
  TermsOfService(
      heading: 'Changes To Our Terms & Conditions',
      details:
          " You acknowledge and agree that <?=Athlink;?> may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at <?=Athlink;?>’s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform <?=Athlink;?> when you stop using the Service. You acknowledge and agree that if <?=Athlink;?> disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.  If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below."),
  TermsOfService(
      heading: 'Modifications to Our app',
      details:
          'Athlink reserves the right to modify, suspend or discontinue, temporarily or permanently, the app or any service to which it connects, with or without notice and without liability to you.'),
  TermsOfService(
      heading: 'Updates to Our app',
      details:
          'Athlink may from time to time provide enhancements or improvements to the features/ functionality of the app, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").  Updates may modify or delete certain features and/or functionalities of the app. You agree that Athlink has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the app to you.  You further agree that all Updates will be (i) deemed to constitute an integral part of the app, and (ii) subject to the terms and conditions of this Agreement'),
  TermsOfService(
      heading: 'Third-Party Services',
      details:
          "We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services '(Third- Party Services)'.  You acknowledge and agree that Athlink shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Athlink does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.  Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions")
];
